# Generated by Django 4.2.24 on 2025-09-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stotra_manjari_admin", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="artist",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["id"], "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="language",
            options={"ordering": ["id"]},
        ),
        migrations.AddField(
            model_name="project",
            name="chapter_prefix",
            field=models.CharField(
                default="chapter_",
                help_text="Prefix to use when generating chapter codes (e.g., 'sarga_', 'adhyaya_').",
                max_length=50,
            ),
        ),
    ]
