# Generated by Django 4.2.24 on 2025-09-04 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stotra_manjari_admin", "0002_alter_artist_options_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="chapter_label",
            field=models.CharField(
                default="Chapter",
                help_text="Label used in chapter titles (e.g., 'Sarga', 'Adhyaya').",
                max_length=50,
            ),
        ),
    ]
