# Generated by Django 4.2.24 on 2025-09-05 00:01

from django.db import migrations, models
import stotra_manjari_admin.models


class Migration(migrations.Migration):

    dependencies = [
        ("stotra_manjari_admin", "0003_project_chapter_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="banner_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=stotra_manjari_admin.models.project_banner_path
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="over_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=stotra_manjari_admin.models.project_cover_path
            ),
        ),
    ]
