# Generated by Django 4.2.24 on 2025-09-05 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stotra_manjari_admin", "0004_project_banner_image_project_over_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="over_image",
            new_name="cover_image",
        ),
    ]
