# Generated by Django 4.2.24 on 2025-09-05 16:19

from django.db import migrations, models
import stotra_manjari_admin.models


class Migration(migrations.Migration):

    dependencies = [
        ("stotra_manjari_admin", "0005_rename_over_image_project_cover_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter", name="code", field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="project",
            name="banner_image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=stotra_manjari_admin.models.OverwriteStorage(),
                upload_to=stotra_manjari_admin.models.project_banner_path,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=stotra_manjari_admin.models.OverwriteStorage(),
                upload_to=stotra_manjari_admin.models.project_cover_path,
            ),
        ),
    ]
