# Generated by Django 4.2.24 on 2025-09-07 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "stotra_manjari_admin",
            "0006_alter_chapter_code_alter_project_banner_image_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="chapter_label",
            field=models.CharField(default="Chapter", max_length=50),
        ),
        migrations.AlterField(
            model_name="project",
            name="chapter_prefix",
            field=models.CharField(default="chapter_", max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="chapter", unique_together={("volume", "code")},
        ),
        migrations.CreateModel(
            name="OrchestrationTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("audio", "Audio Extraction"),
                            ("content", "Content Generation"),
                            ("durations", "Durations Extraction"),
                            ("meanings", "Meanings Generation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("input_params", models.JSONField(default=dict)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("log", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="stotra_manjari_admin.chapter",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orchestration_tasks",
                        to="stotra_manjari_admin.project",
                    ),
                ),
                (
                    "volume",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="stotra_manjari_admin.volume",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"],},
        ),
    ]
