# Generated by Django 4.2.24 on 2025-09-04 13:57

from django.db import migrations, models
import django.db.models.deletion
import provisioning.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "artist_code",
                    models.CharField(
                        blank=True,
                        help_text="3-letter code, e.g. 'sgp' for Sriram Ghanapatigal",
                        max_length=3,
                        null=True,
                        unique=True,
                    ),
                ),
                ("full_name", models.CharField(max_length=255, unique=True)),
                (
                    "formal_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("short_bio", models.TextField(blank=True, null=True)),
                ("image", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={"verbose_name_plural": "Categories",},
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=100, unique=True)),
                ("project_name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("audio_book", "Audio Book"),
                            ("e_book", "E-Book"),
                            ("music_album", "Music Album"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("volume", "Volume-based"),
                            ("chapter", "Chapter-based"),
                            ("standalone", "Standalone"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("overview", models.TextField(blank=True, null=True)),
                ("preview", models.TextField(blank=True, null=True)),
                ("featured", models.BooleanField(default=False)),
                ("published", models.BooleanField(default=False)),
                ("is_premium", models.BooleanField(default=False)),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("price", models.FloatField(default=0.0)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="projects", to="provisioning.category"
                    ),
                ),
                (
                    "languages",
                    models.ManyToManyField(
                        blank=True, related_name="projects", to="provisioning.language"
                    ),
                ),
                (
                    "primary_artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="primary_projects",
                        to="provisioning.artist",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Volume",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("subtitle", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=provisioning.models.volume_thumbnail_path,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="volumes",
                        to="provisioning.project",
                    ),
                ),
            ],
            options={"ordering": ["id"],},
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("key", models.CharField(max_length=50)),
                ("path", models.CharField(max_length=255)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="provisioning.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contributor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("role", models.CharField(max_length=100)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributions",
                        to="provisioning.artist",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributors",
                        to="provisioning.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=100, unique=True)),
                ("index", models.IntegerField()),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("subtitle", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "state",
                    models.IntegerField(
                        choices=[(0, "Hidden"), (1, "Disabled"), (2, "Enabled")],
                        default=2,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="provisioning.project",
                    ),
                ),
                (
                    "volume",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="provisioning.volume",
                    ),
                ),
            ],
            options={"ordering": ["index"],},
        ),
    ]
