"""
Django settings for admin_ui project.

Generated by 'django-admin startproject' using Django 4.2.24.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from django.contrib import admin
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

STATIC_URL = "/static/"

# This is where collectstatic will copy everything
STATIC_ROOT = BASE_DIR / "staticfiles"

# Optional: keep your app-specific static files here
STATICFILES_DIRS = [
    BASE_DIR / "static", # makes admin_ui/static available
    ]

MEDIA_URL = "/media/"
MEDIA_ROOT = "/Volumes/LTFNAS2/data/stotra-manjari/pre-staging/stotra-manjari-assets/projects/"   # staging location

PROJECT_ROOT = MEDIA_ROOT  # staging location

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-8m650o0npq6fhb&e7uz@e-l=_0wq=d3imh@lnl)pua!z(64pry"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

X_FRAME_OPTIONS = "SAMEORIGIN"

# Application definition

INSTALLED_APPS = [
    "jazzmin",
    #"nested_admin", #grappelli, jazzmin, suit, material, jet admin, nested_admin
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "stotra_manjari_admin.apps.StotraManjariAdminConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "admin_ui.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]



WSGI_APPLICATION = "admin_ui.wsgi.application"

# Jazzmin configuration
JAZZMIN_SETTINGS = {
    # Title and branding
    "site_title": "Stotra Manjari Admin",
    "site_header": "Stotra Manjari Admin",
    "site_brand": "",
    "welcome_sign": "Welcome to Stotra Manjari Admin",
    "copyright": "© 2025 Amrutham",

    # Logo paths (relative to STATIC_URL)
    "site_logo": "images/logo_200_200.png",           # Top-left logo
    "site_logo_classes": "img-circle",        # CSS classes (rounded, circle, etc.)
    "site_icon": "images/logo_200_200.png",           # Favicon

    # Top menu links
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Documentation", "url": "https://docs.djangoproject.com/", "new_window": True},
    ],

    # Sidebar
    "show_sidebar": True,
    "navigation_expanded": True,

    # Icons (FontAwesome or Jazzmin icons)
    # Icons (FontAwesome or Jazzmin icons)
    "icons": {
        # Provisioning models
        "stotra_manjari_admin.Project": "fas fa-book",
        "stotra_manjari_admin.Volume": "fas fa-layer-group",
        "stotra_manjari_admin.Chapter": "fas fa-scroll",
        "stotra_manjari_admin.Artist": "fas fa-user",
        "stotra_manjari_admin.Category": "fas fa-tags",
        "stotra_manjari_admin.Language": "fas fa-language",
        "stotra_manjari_admin.ProjectImage": "fas fa-image",
        "provisstotra_manjari_adminioning.Contributor": "fas fa-users",

        # Orchestration models
        "orchestration.AudioExtraction": "fas fa-music",
        "orchestration.ContentGeneration": "fas fa-file-alt",
        "orchestration.DurationsExtraction": "fas fa-clock",
        "orchestration.MeaningsGeneration": "fas fa-lightbulb",

        # Deployment models
        "deployment.PreStagingToStaging": "fas fa-cloud-upload-alt",
        "deployment.StagingToProduction": "fas fa-rocket",
    },


    # UI tweaks
    "hide_apps": [],
    "hide_models": [],

    "order_with_respect_to": [
        "stotra_manjari_admin",
        "stotra_manjari_admin.Artist",
        "stotra_manjari_admin.Category",
        "stotra_manjari_admin.Language",
        "stotra_manjari_admin.Project",
        "stotra_manjari_admin.Volume",
        "stotra_manjari_admin.Chapter",
        "orchestration",
        "deployment",
    ],

    # Custom colors (pick your palette)
    "custom_css": "css/custom_admin.css",
    "custom_js": None,
    "show_ui_builder": True,  # 🔥 lets you play with colors live
}

# Optional: additional Jazzmin UI tweaks
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-danger",
    "accent": "accent-warning",
    "navbar": "navbar-primary navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-light-warning",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,
    "theme": "cyborg",
    "dark_mode_theme": "cyborg",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    "custom_css": "css/custom_admin.css",
    "actions_sticky_top": True,
}
# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True



# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
